### PR TITLE
Event dashboard

### PR DESCRIPTION
**Pull request by Khalidmamdou7**
# Implement UI for Event Management Dashboard and Sidebar

### Description
This pull request implements the UI for the event management dashboard and the sidebar of the event management. The changes include the creation of the necessary React components and CSS styles to display the event dashboard and sidebar according to the design specifications.

### Changes Made 

I have followed the following file structure for the React components:

```
-src
----genericComponents
----layouts
-------eventSidenav
---------------EventSidenav.jsx
---------------eventSidenav.css
-------navbar (could be added here) @Omar-Al-Sharif 
----pages
-------eventDashboard
--------------EventDashboard.jsx
--------------EventDashboard.css
--------------actionList
------------------ActionList.jsx
------------------actionList.css
--------------card
------------------Card.jsx
------------------card.css
--------------reportTable
------------------ReportTable.jsx
------------------reportTable.css
--------------share
------------------Share.jsx
------------------share.css
--------------services.js
----utils
-------api.js
-.env.staging.example

```

In the `eventSidenav` layout, I have implemented the sidebar navigation menu, which includes links to different sections of the event management dashboard. 

In the `eventDashboard` page, I have implemented the main content section, which includes the event overview and the report table.

### Screenshots showing Responsiveness 🤩
image
image
image
image
image
image

### Known Issues 😔
- There is a bug in the responsiveness of the share section in mobile sizes where another scroll bar appears instead of the main scroll bar.

- Copy to clipboard button is not function
- Should I add id attributes for testing ? Which components would needs ids?

### Future Work 
- Integrate the sideNav with the backend to update status of publishing steps.
- Integrate the navbar with the event dashboard
- Unit testing to ensure the functionality of the components.
- Implement the functionality of the copy to clipboard button
- Add id attributes for to-be-tested components if necessary

### Checklist
- [x] Implemented UI for the Event Management sidebar
- [x] Implemented UI for the Event Management Dashboard
- [x] Created necessary React components and CSS styles
- [x] Integrated with the backend to fetch and display event data dynamically
- [ ] Integrate the sideNav with the backend to update status of publishing steps.
- [ ] Integrated the navbar (waiting for @Omar-Al-Sharif to make the navbar component)
- [x] Added unit testing to ensure the functionality of the components
- [ ] Fixed the known bugs
- [ ] Add id attributes for to-be-tested components if necessary

### Additional Notes 
Please review and provide feedback on the implemented UI for the event management dashboard and sidebar. Thank you!

### CODE REVIEW

**Comment by Khalidmamdou7** [comment]
## New updates

The previous commits was made to integrate the Ui components of the `Event Dashboard` page with the backend, in order to do this the following changes has been made:

- Created an `api.js` file in `src/utils` which include a helper function that fetches data from urls using axios
- Created an env file to store the api domain (an env.example was pushed to the repo)
- Created a `services.js` file inside `eventDashboard` component folder to include helper functions that retrieve needed data from the api

The pull request post will be updated with these data

**Review by Omar-Al-Sharif — CHANGES_REQUESTED** [review]
## Pull Request Review

### Overall

- [x] Code is well-organized and easy to understand.
- [x] Directory names follow the name convention of the project .

### Next Steps


- [x] We need to unite and agree upon one naming convention for files and directory names
   - I suggest this [naming convention](https://betterprogramming.pub/an-opinionated-guide-to-react-folder-structure-file-naming-8b723d39a0d6)
- [ ] During the next phase, we need to add IDs, to each html element in the jsx files, for the testing team (not urgent, can be done after merging)

### Questions:
- Could you provide the documentation link you used for the axios library?


### Additional Notes

- Great job on this feature! I really appreciate the thorough documentation 👏

**Comment by Khalidmamdou7** [comment]
Thank you ya Amoor for your feedback!


>     * [ ]  We need to unite and agree upon one naming convention for files and directory names
>       
>       * I suggest this [naming convention](https://betterprogramming.pub/an-opinionated-guide-to-react-folder-structure-file-naming-8b723d39a0d6)

I updated the names for the directories and files according to the article you mentioned,  PascalCase for jsx files and dash-case for other files and directories.

>     * Could you provide the documentation link you used for the axios library?
Sure, I used the 4th method mentioned [here](https://statusneo.com/different-ways-to-fetch-data-from-api-in-reactjs/). I created a wrapper function in the utils folder to only use it with the endpoint (as I have mentioned before)

>     * [ ]  During the next phase, we need to add IDs, to each html element in the jsx files, for the testing team (not urgent, can be done after merging)
In sha allah

**Review by Omar-Al-Sharif — APPROVED** [review]
Reviewed, thank you Khalood keep up the good work 👏

**Pull request merged**
